### ISSUE TITLE
Pandas below 2 as a requirement

### ISSUE THREAD

**Issue by miks2021** [streamlit/gsheets-connection#20]
Is there any particular reason why the package requires pandas below version 2? Streamlit itself works fine with later versions. https://github.com/streamlit/gsheets-connection/blob/6d50cc196602cac909ffc9a47668b525ada7ccf7/setup.py#L13C1-L14C1

**Comment by gatto** [comment]
This issue is now blocking me to use streamlit with ANYTHING because the installed version of pandas < v2 throws error right on import (on `import pandas as pd`)
