### ISSUE TITLE
Error installing package with command "pip install git+https://github.com/sfc-gh-jcarroll/st-connection-prpr.git#subdirectory=gsheets_connection"

### ISSUE THREAD

**Issue by phong-ssk** [streamlit/gsheets-connection#4]
I encountered an issue while trying to install a package using the pip install command. Here are the details:

Command:
pip install git+https://github.com/sfc-gh-jcarroll/st-connection-prpr.git#subdirectory=gsheets_connection

Error Message: 
ERROR: git+https://github.com/sfc-gh-jcarroll/st-connection-prpr.git#subdirectory=gsheets_connection does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
----Detail -----
Collecting git+https://github.com/sfc-gh-jcarroll/st-connection-prpr.git#subdirectory=gsheets_connection
  Cloning https://github.com/sfc-gh-jcarroll/st-connection-prpr.git to c:\users\phong.lh\appdata\local\temp\pip-req-build-mztcj_pe
  Running command git clone --filter=blob:none --quiet https://github.com/sfc-gh-jcarroll/st-connection-prpr.git 'C:\Users\phong.lh\AppData\Local\Temp\pip-req-build-mztcj_pe'
  Resolved https://github.com/sfc-gh-jcarroll/st-connection-prpr.git to commit a7081765a584cad93c8b59ac1e53696977ead619

ERROR: git+https://github.com/sfc-gh-jcarroll/st-connection-prpr.git#subdirectory=gsheets_connection does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

I hope you have time to show me how to get the error fix. Thanks!

**Comment by sfc-gh-jcarroll** [comment]
Hi @phong-ssk @NathanJGaul

Sorry for this! We need to update the install instructions. Will work on getting it updated later today.

You should be able to install like this:
```
pip install git+https://github.com/streamlit/gsheets-connection
```

Let me know if you still have trouble with that.

**Comment by NathanJGaul** [comment]
> Hi @phong-ssk @NathanJGaul
> 
> Sorry for this! We need to update the install instructions. Will work on getting it updated later today.
> 
> You should be able to install like this:
> 
> ```
> pip install git+https://github.com/streamlit/gsheets-connection
> ```
> 
> Let me know if you still have trouble with that.

This is working for me!

**Comment by phong-ssk** [comment]
[heart]         Le Hoang Phong (Phong Khoa hoc... reacted to your message:
________________________________

**Comment by phong-ssk** [comment]
> Hi @phong-ssk @NathanJGaul
> 
> Sorry for this! We need to update the install instructions. Will work on getting it updated later today.
> 
> You should be able to install like this:
> 
> ```
> pip install git+https://github.com/streamlit/gsheets-connection
> ```
> 
> Let me know if you still have trouble with that.



> Hi @phong-ssk @NathanJGaul
> 
> Sorry for this! We need to update the install instructions. Will work on getting it updated later today.
> 
> You should be able to install like this:
> 
> ```
> pip install git+https://github.com/streamlit/gsheets-connection
> ```
> 
> Let me know if you still have trouble with that.

Dear Sir,
It works for me! Many thanks for your help! 
"Cảm ơn rất nhiều!" :)
